export interface ITescoProduct {
    image: string,
    superDepartment: string,
    tpnb: number,
    ContentsMeasureType: string,
    name: string,
    UnitOfSale: 1,
    AverageSellingUnitWeight: number,
    description: string,
    UnitQuantity: string,
    id: number,
    ContentsQuantity: number,
    department: string,
    price: number,
    unitprice: number,
    quantity: number,
    isChecked: boolean,
    timesAddedToShoppingList: number,
}
