export enum StateKeys {
    CURRENT_PRODUCT_SET = 'CURRENT_PRODUCT_SET',
    CURRENT_SEARCH_SET = 'CURRENT_SEARCH_SET',

    SEARCH_SETTINGS = 'SEARCH_SETTINGS',
    SEARCH_SETTINGS_SET = 'SEARCH_SETTINGS_SET',

    SHOPPING_LIST_PRODUCT_UPDATE = 'SHOPPING_LIST_PRODUCT_UPDATE',
    SHOPPING_LIST_PRODUCTS = 'SHOPPING_LIST_PRODUCTS',
    SHOPPING_LIST_PRODUCTS_ADD = 'SHOPPING_LIST_PRODUCTS_ADD',
    SHOPPING_LIST_PRODUCTS_REMOVE = 'SHOPPING_LIST_PRODUCTS_REMOVE',
    SHOPPING_LIST_UNCHECKED = 'SHOPPING_LIST_UNCHECKED',
    SHOPPING_LIST_UNCHECKED_SET = 'SHOPPING_LIST_UNCHECKED_SET',
    SHOPPING_LIST_CHECKED = 'SHOPPING_LIST_CHECKED',
    SHOPPING_LIST_CHECKED_SET = 'SHOPPING_LIST_CHECKED_SET',

    SHOPPING_LIST_SETTINGS = 'SHOPPING_LIST_SETTINGS',
    SHOPPING_LIST_SETTINGS_SET = 'SHOPPING_LIST_SETTINGS_SET',

    SELECTED_SHOP = 'SELECTED_SHOP',
    SELECTED_SHOP_SET = 'SELECTED_SHOP_SET',

    USER = 'USER',
    USER_SET = 'USER_SET',
}
